FROM node:alpine
#WORKDIR "/app"
RUN echo fs.inotify.max_user_watches=524288 
RUN tee -a /etc/sysctl.conf
RUN sysctl -p
COPY ./package.json ./
RUN npm install
RUN npm i nodemon -g
COPY . .
CMD ["npm", "run", "dev"]