FROM node:alpine
#WORKDIR /
RUN apt-get update
RUN apt-get -y install sudo
RUN echo fs.inotify.max_user_watches=524288 
RUN sudo tee -a /etc/sysctl.conf
RUN sudo sysctl -p  
COPY ./package.json ./
RUN npm install
RUN npm i nodemon -g
COPY . .
CMD ["npm", "run", "dev"]