apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-Deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      label:
        component: web
    spec:
      containers:
        - name: client
          image:
