apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 2
  selector:
    matchLables:
      component: worker
  template:
    metadata:
        Labels:
            component: worker
